# Site Settings
title: "API documentation"

# Where things are
collections:
  endpoints:
    output: true
    permalink: /:title

# Handling Reading
safe: false
include: ["_endpoints"]
exclude: ["README.md"]

# Markdown Processors
kramdown:
  input: GFM
