# Site Settings
title: "API documentation"

# Where things are
sass:
  sass_dir: _assets/css
collections:
  endpoints:
    output: true
    permalink: :title

# Handling Reading
safe: false
include: ["_endpoints", "_assets"]
exclude: ["README.md"]

# Markdown Processors
kramdown:
  input: GFM
