# Site properties
title: "API documentation"
description: "Simple flexible static API documentation."
url: "https://vivi90.github.io/a-la-carte"
baseurl: ""

# Where things are
collections:
  endpoints:
    output: true
    permalink: :title

# Handling Reading
safe: false
exclude: ["README.md", "LICENSE.txt"]

# Markdown Processors
kramdown:
  input: GFM
